"""empty message

Revision ID: 16653e4ba4c6
Revises: e8f2a701061d
Create Date: 2024-07-07 22:19:25.232913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16653e4ba4c6'
down_revision = 'e8f2a701061d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
